services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_event_exception.exception_event_listener:
        class: 'Jalismrs\Symfony\Bundle\JalismrsExceptionEventBundle\EventListener\ExceptionEventListener'

    Jalismrs\Symfony\Bundle\JalismrsExceptionEventBundle\EventListener\ExceptionEventListener: '@jalismrs_event_exception.exception_event_listener'
