services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    event_exception.exception_event_subscriber:
        class: 'Jalismrs\EventExceptionBundle\ExceptionEventSubscriber'

    Jalismrs\EventExceptionBundle\ExceptionEventSubscriber: '@event_exception.exception_event_subscriber'
