services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_event_exception.exception_event_subscriber:
        class: 'Jalismrs\Symfony\Bundle\JalismrsExceptionEventBundle\EventSubscriber\ExceptionEventSubscriber'

    Jalismrs\Symfony\Bundle\JalismrsExceptionEventBundle\EventSubscriber\ExceptionEventSubscriber: '@jalismrs_event_exception.exception_event_subscriber'
